CI/CD for polybot111

diff --git a/.github/workflows/yolo5-deployment.yaml b/.github/workflows/yolo5-deployment.yaml
--- a/.github/workflows/yolo5-deployment.yaml
+++ b/.github/workflows/yolo5-deployment.yaml
@@ -20,10 +20,6 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
 
-    - name: Set up SSH key
-      run: |
-        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
-        chmod 600 private_key.pem
 
     - name: Set up Docker Build
       uses: docker/setup-buildx-action@v2
@@ -31,14 +27,16 @@ jobs:
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_PASSWORD }}
+        username: ${{ secrets.DOCKER_REPO_USERNAME }}
+        password: ${{ secrets.DOCKER_REPO_PASSWORD }}
 
     - name: Build and push Docker image
       run: |
         cd yolo5
-        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest .
-        docker push ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest
+        YOLO5_IMAGE_NAME=image_yolo5_am_project:${{ github.run_number }}
+        docker build -t $YOLO5_IMAGE_NAME .
+        docker tag $POLY_BOT_IMAGE_NAME ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
+        docker push ${{ secrets.DOCKER_REPO_USERNAME }}/$YOLO5_IMAGE_NAME
 
     - name: Get EC2 instance ID
       run: |
@@ -49,22 +47,22 @@ jobs:
       id: get_public_ip
       run: |
         EC2_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
-        echo "EC2_PUBLIC_IP_ASG=$EC2_PUBLIC_IP_ASG" >> $GITHUB_ENV
+#        echo "EC2_PUBLIC_IP_ASG=$EC2_PUBLIC_IP_ASG" >> $GITHUB_ENV
 
     - name: Deploy to AWS EC2
       run: |      
         # Retry SSH connection up to 5 times with a delay
         for attempt in {1..5}; do
           echo "Attempt $attempt to connect to ${{ env.EC2_PUBLIC_IP }}"
-          if ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "echo 'SSH connection successful'"; then
-            echo "SSH connection successful to ${{ env.EC2_PUBLIC_IP_ASG }}"
-            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "sudo docker stop yolo5* || true"
-            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "sudo docker rm yolo5* || true"
-            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
-            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.EC2_PUBLIC_IP_ASG }} "sudo docker run -d --name yolo5 ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
+          if ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@$EC2_PUBLIC_IP "echo 'SSH connection successful'"; then
+            echo "SSH connection successful to $EC2_PUBLIC_IP"
+            ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@$EC2_PUBLIC_IP "sudo docker stop my_yolo5_test || true"
+            ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@$EC2_PUBLIC_IP "sudo docker rm yolo5* || true"
+            ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@$EC2_PUBLIC_IP "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"
+            ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@$EC2_PUBLIC_IP "sudo docker run -d --name my_yolo5_test ${{ secrets.DOCKER_REPO_USERNAME }}/$YOLO5_IMAGE_NAME"
             break
           else
-            echo "SSH connection to ${{ env.EC2_PUBLIC_IP_ASG }} failed. Retrying in 10 seconds..."
+            echo "SSH connection to ubuntu@$EC2_PUBLIC_IP failed. Retrying in 10 seconds..."
             sleep 10
           fi
         done
